### ISSUE TITLE
> Could not read script 'D:\AnimeArcaneGAN_Mobile_2023_0711\node_modules\@react-native-community\cli-platform-android\native_modules.gradle' as it does not exist.

### ISSUE THREAD

**Issue by linnaok** [juanjaho/animeGAN_Mobile#4]
> Could not read script 'D:\AnimeArcaneGAN_Mobile_2023_0711\node_modules\@react-native-community\cli-platform-android\native_modules.gradle' as it does not exist.

**Comment by juanjaho** [comment]
Hello, are you able to try out the following:
https://stackoverflow.com/questions/59422584/react-native-build-failed-in-android-react-native-community-cli-platform-andro

**Comment by juanjaho** [comment]
Closed due to inactivity
